
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence DABA --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence avg --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence RLR --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence flame --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence krum --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence fltrust --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence DABA --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence avg --malicious 0.25 --attack badnet   
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence RLR --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence flame --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence krum --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence fltrust --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence DABA --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence avg --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence RLR --malicious 0.25 --type_poi cs     
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence flame --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence krum --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence fltrust --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence DABA --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence avg --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence RLR --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence flame --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence krum --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet50 --iid 1 --defence fltrust --malicious 0.25 --type_poi pgd
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence DABA --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence avg --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence RLR --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence flame --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence krum --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence fltrust --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence DABA --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence avg --malicious 0.25 --attack badnet   
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence RLR --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence flame --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence krum --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence fltrust --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence DABA --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence avg --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence RLR --malicious 0.25 --type_poi cs     
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence flame --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence krum --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence fltrust --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence DABA --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence avg --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence RLR --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence flame --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence krum --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model resnet101 --iid 1 --defence fltrust --malicious 0.25 --type_poi pgd
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence DABA --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence avg --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence RLR --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence flame --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence krum --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence fltrust --malicious 0.25 --attack dba 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence DABA --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence avg --malicious 0.25 --attack badnet   
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence RLR --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence flame --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence krum --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence fltrust --malicious 0.25 --attack badnet 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence DABA --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence avg --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence RLR --malicious 0.25 --type_poi cs     
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence flame --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence krum --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence fltrust --malicious 0.25 --type_poi cs 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence DABA --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence avg --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence RLR --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence flame --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence krum --malicious 0.25 --type_poi pgd 
python3.8 main.py --dataset cifar --model mobilenetv2 --iid 1 --defence fltrust --malicious 0.25 --type_poi pgd 