python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.20 --attack dba 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.20 --attack dba 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.20 --attack dba 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.20 --attack dba 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.20 --attack dba 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.20 --attack dba 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.20 --attack badnet 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.20 --attack badnet   
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.20 --attack badnet 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.20 --attack badnet 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.20 --attack badnet 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.20 --attack badnet 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.20 --type_poi cs 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.20 --type_poi cs 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.20 --type_poi cs     
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.20 --type_poi cs 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.20 --type_poi cs 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.20 --type_poi cs 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.20 --type_poi pgd 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.20 --type_poi pgd 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.20 --type_poi pgd 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.20 --type_poi pgd 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.20 --type_poi pgd 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.20 --type_poi pgd 
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.27 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.27 --attack dba   
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.27 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.27 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.27 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.27 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.27 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.27 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.27 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.27 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.27 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.27 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.27 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.27 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.27 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.27 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.27 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.27 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.27 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.27 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.27 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.27 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.27 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.27 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.35 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.35 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.35 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.35 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.35 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.35 --attack dba
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.35 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.35 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.35 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.35 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.35 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.35 --attack badnet
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.35 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.35 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.35 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.35 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.35 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.35 --type_poi cs
python3.8 main.py --dataset fashion_mnist --iid 0 --defence DABA --malicious 0.35 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence avg --malicious 0.35 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence RLR --malicious 0.35 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence flame --malicious 0.35 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence krum --malicious 0.35 --type_poi pgd
python3.8 main.py --dataset fashion_mnist --iid 0 --defence fltrust --malicious 0.35 --type_poi pgd